import type { Metadata } from 'next';
import { ExternalLink, FileCheck, Scale, ShieldCheck } from 'lucide-react';
import EmergencyHeader from '@/components/EmergencyHeader';
import { pageMetadata } from '@/lib/seo';

export const metadata: Metadata = pageMetadata({ title: 'Florida Bail Information & Resource Guides', description: 'Read source-based Florida bail information covering premiums, collateral, agent licensing, court-controlled release, warrants, and official county resources.', path: '/resources' });
const sources = [
  { title: 'Florida DFS bail bonds overview', description: 'Consumer guidance on licensing, premiums, collateral, receipts, contracts, forfeiture, and bond discharge.', url: 'https://www.myfloridacfo.com/division/consumers/understanding-insurance/bail-bonds-overview' },
  { title: 'Florida Statutes, Chapter 903', description: 'The official Florida Legislature chapter governing bail and related court procedures.', url: 'https://www.leg.state.fl.us/Statutes/index.cfm?App_mode=Display_Statute&URL=0900-0999/0903/0903ContentsIndex.html' },
  { title: 'Florida Statutes, Chapter 648', description: 'The official Florida Legislature chapter governing bail bond agents.', url: 'https://www.leg.state.fl.us/Statutes/index.cfm?App_mode=Display_Statute&URL=0600-0699/0648/0648ContentsIndex.html' },
  { title: 'Florida license search', description: 'Check the status and identity of an individual insurance or bail bond licensee before doing business.', url: 'https://licenseesearch.fldfs.com/' },
  { title: 'FDLE Wanted Persons Search', description: 'Public warrant information reported by agencies, with FDLE warnings about currency and verification.', url: 'https://pas.fdle.state.fl.us/pas/restricted/PAS/person/WantedPersons.jsf' },
];
export default function ResourcesPage() { return <main className="min-h-screen bg-slate-950 text-slate-200"><EmergencyHeader /><section className="border-b border-white/5 bg-slate-900/50 py-20"><div className="mx-auto max-w-5xl px-6"><p className="text-sm font-bold uppercase tracking-[0.2em] text-yellow-500">Primary sources</p><h1 className="mt-4 text-5xl font-serif font-bold text-white">Florida bail information resources</h1><p className="mt-6 max-w-3xl text-lg leading-relaxed text-slate-400">Start with government sources. Website summaries cannot account for every charge, court order, contract, hold, or later legal change.</p></div></section><section className="py-16"><div className="mx-auto max-w-5xl space-y-6 px-6">{sources.map((source) => <a key={source.url} href={source.url} target="_blank" rel="noopener noreferrer" className="block rounded-xl border border-slate-800 bg-slate-900/50 p-7 transition-colors hover:border-yellow-500"><h2 className="flex items-center gap-2 text-xl font-bold text-white">{source.title}<ExternalLink className="h-4 w-4 text-yellow-500" /></h2><p className="mt-3 leading-relaxed text-slate-400">{source.description}</p></a>)}</div></section><section className="border-t border-white/5 bg-slate-900/30 py-16"><div className="mx-auto grid max-w-5xl gap-6 px-6 md:grid-cols-3"><div className="rounded-xl border border-slate-800 p-6"><FileCheck className="h-6 w-6 text-yellow-500" /><h2 className="mt-4 font-bold text-white">Read the contract</h2><p className="mt-3 text-sm leading-relaxed text-slate-400">Review premium, collateral, indemnitor duties, payment charges, surrender, and refund terms before signing.</p></div><div className="rounded-xl border border-slate-800 p-6"><ShieldCheck className="h-6 w-6 text-yellow-500" /><h2 className="mt-4 font-bold text-white">Verify the license</h2><p className="mt-3 text-sm leading-relaxed text-slate-400">Confirm the individual agent through the official state database rather than relying on a badge or website claim.</p></div><div className="rounded-xl border border-slate-800 p-6"><Scale className="h-6 w-6 text-yellow-500" /><h2 className="mt-4 font-bold text-white">Get legal advice</h2><p className="mt-3 text-sm leading-relaxed text-slate-400">A qualified attorney can interpret court orders and advise on a specific criminal or immigration matter.</p></div></div></section></main>; }
