import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowRight, ExternalLink, MapPin } from 'lucide-react';
import EmergencyHeader from '@/components/EmergencyHeader';
import { counties } from '@/lib/data';
import { pageMetadata } from '@/lib/seo';

export const metadata: Metadata = pageMetadata({ title: 'Florida Bail Bonds & County Jail Directory', description: 'Browse selected Florida county and city guides with detention contacts, official inmate-search resources, local agencies, and general bail information.', path: '/locations' });
export default function LocationsPage() { const totalCities = counties.reduce((sum, county) => sum + (county.cities?.length || 0), 0); return <main className="min-h-screen bg-slate-950 text-slate-200"><EmergencyHeader /><section className="border-b border-white/5 bg-slate-900/50 py-20"><div className="mx-auto max-w-6xl px-6"><p className="text-sm font-bold uppercase tracking-[0.2em] text-yellow-500">Current coverage</p><h1 className="mt-4 text-5xl font-serif font-bold text-white">Florida county and city directory</h1><p className="mt-6 max-w-3xl text-lg leading-relaxed text-slate-400">The directory currently contains {counties.length} county guides and {totalCities} city guides. A listing is informational and does not represent a physical Bond Florida office or local agent.</p></div></section><section className="py-16"><div className="mx-auto grid max-w-6xl gap-6 px-6 md:grid-cols-2">{counties.map((county) => <article key={county.slug} className="rounded-xl border border-slate-800 bg-slate-900/50 p-7"><MapPin className="h-6 w-6 text-yellow-500" /><h2 className="mt-4 text-2xl font-bold text-white"><Link href={`/county/${county.slug}`}>{county.name}</Link></h2><p className="mt-3 text-slate-400">Primary listed facility: {county.jail.name}</p><a className="mt-4 inline-flex items-center gap-1 text-sm text-yellow-500 underline" href={county.jail.inmateSearchUrl} target="_blank" rel="noopener noreferrer">Official inmate resource <ExternalLink className="h-4 w-4" /></a><ul className="mt-6 flex flex-wrap gap-2">{county.cities?.map((city) => <li key={city.slug}><Link className="inline-flex items-center gap-1 rounded-full border border-slate-700 px-3 py-1.5 text-sm text-slate-300" href={`/county/${county.slug}/${city.slug}`}>{city.name}<ArrowRight className="h-3 w-3" /></Link></li>)}</ul></article>)}</div></section></main>; }
