import Link from 'next/link';
import { ArrowRight, BookOpen, Building2, ExternalLink, MapPin, Search, ShieldCheck } from 'lucide-react';
import EmergencyHeader from '@/components/EmergencyHeader';
import { counties } from '@/lib/data';
import { services } from '@/lib/services';
import { pageMetadata } from '@/lib/seo';

export const metadata = pageMetadata({ title: 'Florida Bail Bonds & Inmate Search | Bond Florida', description: 'Find Florida county jail contacts, official inmate-search links, source-based bail information, and selected local agency guides in the Bond Florida directory.' });

export default function Home() {
  return (
    <main className="min-h-screen bg-slate-950 text-slate-200">
      <EmergencyHeader />
      <section className="border-b border-white/5 bg-gradient-to-b from-slate-900 to-slate-950 py-24"><div className="mx-auto max-w-6xl px-6 text-center"><p className="text-sm font-bold uppercase tracking-[0.22em] text-yellow-500">Florida public-resource directory</p><h1 className="mx-auto mt-5 max-w-4xl text-5xl font-serif font-bold text-white md:text-7xl">Find the responsible jail, inmate search, and official source</h1><p className="mx-auto mt-7 max-w-3xl text-xl leading-relaxed text-slate-400">Bond Florida organizes public county contacts and general bail information. Verify custody, court requirements, and release details with the responsible agency.</p><div className="mt-10 flex flex-col justify-center gap-4 sm:flex-row"><Link className="inline-flex items-center justify-center gap-2 rounded-lg bg-yellow-500 px-6 py-4 font-bold text-slate-950" href="/locations"><MapPin className="h-5 w-5" />Browse county directory</Link><Link className="inline-flex items-center justify-center gap-2 rounded-lg border border-slate-700 px-6 py-4 font-bold text-white" href="/resources"><BookOpen className="h-5 w-5" />Read verified resources</Link></div></div></section>
      <section className="py-20"><div className="mx-auto max-w-6xl px-6"><h2 className="text-3xl font-serif font-bold text-white">County jail resources</h2><p className="mt-4 max-w-3xl leading-relaxed text-slate-400">Each county page links to the official inmate-search or corrections resource stored for that jurisdiction. Public records can lag, so call the agency for urgent verification.</p><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{counties.map((county) => <Link key={county.slug} href={`/county/${county.slug}`} className="rounded-xl border border-slate-800 bg-slate-900/50 p-6 transition-colors hover:border-yellow-500"><Building2 className="h-6 w-6 text-yellow-500" /><h3 className="mt-4 font-bold text-white">{county.name}</h3><p className="mt-2 text-sm text-slate-500">{county.jail.name}</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-bold text-yellow-500">Open guide <ArrowRight className="h-4 w-4" /></span></Link>)}</div></div></section>
      <section className="border-y border-white/5 bg-slate-900/30 py-20"><div className="mx-auto max-w-6xl px-6"><h2 className="text-3xl font-serif font-bold text-white">Source-based information guides</h2><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{services.map((service) => { const Icon = service.icon; return <Link key={service.slug} href={`/services/${service.slug}`} className="rounded-xl border border-slate-800 bg-slate-950/60 p-6"><Icon className="h-6 w-6 text-yellow-500" /><h3 className="mt-4 font-bold text-white">{service.title}</h3><p className="mt-3 text-sm leading-relaxed text-slate-400">{service.shortDescription}</p></Link>; })}</div></div></section>
      <section className="py-20"><div className="mx-auto grid max-w-6xl gap-8 px-6 md:grid-cols-3"><div className="rounded-xl border border-slate-800 p-7"><Search className="h-6 w-6 text-yellow-500" /><h2 className="mt-4 text-xl font-bold text-white">Verify custody first</h2><p className="mt-3 leading-relaxed text-slate-400">Use the county&apos;s official search and confirm identifying information before relying on a result.</p></div><div className="rounded-xl border border-slate-800 p-7"><ShieldCheck className="h-6 w-6 text-yellow-500" /><h2 className="mt-4 text-xl font-bold text-white">Verify private providers</h2><p className="mt-3 leading-relaxed text-slate-400">Check an individual bail bond agent through Florida&apos;s official license search before sharing money or identification.</p><a className="mt-4 inline-flex items-center gap-1 text-sm font-bold text-yellow-500 underline" href="https://licenseesearch.fldfs.com/" target="_blank" rel="noopener noreferrer">Florida license search <ExternalLink className="h-4 w-4" /></a></div><div className="rounded-xl border border-slate-800 p-7"><BookOpen className="h-6 w-6 text-yellow-500" /><h2 className="mt-4 text-xl font-bold text-white">No release promises</h2><p className="mt-3 leading-relaxed text-slate-400">Courts and detention agencies control custody. Timing depends on the case, holds, processing, and facility operations.</p></div></div></section>
    </main>
  );
}
